import { UserRole } from "@prisma/client";
import {
  PERMISSIONS,
  type Permission,
} from "./permissions.js";

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  SISWA: [
    PERMISSIONS.PROFILE_READ_OWN,
    PERMISSIONS.GRADES_READ_OWN,
    PERMISSIONS.TRANSCRIPT_READ_OWN,
    PERMISSIONS.DIPLOMA_READ_OWN,
    PERMISSIONS.CERTIFICATE_READ_OWN,
  ],

  GURU: [
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.GRADES_READ,
    PERMISSIONS.GRADES_CREATE,
    PERMISSIONS.GRADES_UPDATE,
  ],

  STAF_TU: [
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.STUDENTS_CREATE,
    PERMISSIONS.STUDENTS_UPDATE,
    PERMISSIONS.STUDENTS_DELETE,

    PERMISSIONS.TEACHERS_READ,
    PERMISSIONS.TEACHERS_CREATE,
    PERMISSIONS.TEACHERS_UPDATE,

    PERMISSIONS.SUBJECTS_READ,
    PERMISSIONS.SUBJECTS_CREATE,
    PERMISSIONS.SUBJECTS_UPDATE,

    PERMISSIONS.CLASSES_READ,
    PERMISSIONS.CLASSES_CREATE,
    PERMISSIONS.CLASSES_UPDATE,

    PERMISSIONS.GRADES_READ,
    PERMISSIONS.TRANSCRIPT_MANAGE,

    PERMISSIONS.DIPLOMA_READ,
    PERMISSIONS.DIPLOMA_MANAGE,

    PERMISSIONS.CERTIFICATE_READ,
    PERMISSIONS.CERTIFICATE_MANAGE,
  ],

  KEPALA_SEKOLAH: [
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.TEACHERS_READ,
    PERMISSIONS.GRADES_READ,
    PERMISSIONS.TRANSCRIPT_READ,
    PERMISSIONS.DIPLOMA_READ,
    PERMISSIONS.DIPLOMA_APPROVE,
    PERMISSIONS.CERTIFICATE_READ,
    PERMISSIONS.CERTIFICATE_APPROVE,
    PERMISSIONS.VERIFICATION_READ,
    PERMISSIONS.VERIFICATION_APPROVE,
    PERMISSIONS.AUDIT_READ,
  ],

  MITRA_INDUSTRI: [
    PERMISSIONS.VERIFICATION_CREATE,
    PERMISSIONS.VERIFICATION_READ,
  ],
};